### ISSUE TITLE
some functions are missing in the loss_fn.py

### ISSUE THREAD

**Issue by h4nwei** [EliotChenKJ/Guided-Correspondence-Loss#1]
Hi @EliotChenKJ ,

Thanks for the excellent work. There are some function are missing in the loss_fn.py, such as batch_patch_extraction, compute_cosine_distance, and compute_l2_distance. Hope to see your updates.

**Comment by EliotChenKJ** [comment]
Thanks ~ Already update the file. Feel free to contact me if something goes wrong.
