### ISSUE TITLE
Name 'batch_patch_extraction' is not defined

### ISSUE THREAD

**Issue by MyNiuuu** [EliotChenKJ/Guided-Correspondence-Loss#2]
Thanks for the great work! 
I was running the inference codes when I found some functions missing in `loss_fn.py` with the error: 
`name 'batch_patch_extraction' is not defined.`

Could you please upload the corresponding functions? Thanks a lot!

**Comment by EliotChenKJ** [comment]
Thanks~ already upload the missed function, if anything can't run properly, please contact me, i will reply as soon as i can.

**Comment by MyNiuuu** [comment]
Thanks a lot! I am sorry for the late reply, and thank you so much for the quick help!
